sudo: required
services:
  - docker

before_install:
  - docker build -t drewminns/docker-react-nginx -f dev.Dockerfile .

script:
  -  docker run drewminns/docker-react-nginx npm run test -- --coverage